apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.appName }}
  labels:
    project: roboshop
    app: {{ .Values.appName }}
data:
  {{- range $key, $value := .Values.configMapData }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}

