apiVersion: apps/v1
kind: Deployment
  {{- template "app.metadata" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
{{ include "app.labels" . | indent 6 }}
  template:
    metadata:
      labels:
{{ include "app.labels" . | indent 8 }}
    spec:
      containers:
      - name: roboshop-{{ .Values.appName }}
        image: 739561048503.dkr.ecr.us-east-1.amazonaws.com/{{ .Values.appName }}:{{ .Values.imageTag }}
        envFrom:
        - secretRef:
            name: {{ .Values.appName }}
        readinessProbe:
          httpGet:
            path: /health
            port: {{ .Values.service.port }}
          initialDelaySeconds: 5
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /health
            port: {{ .Values.service.port }}
          initialDelaySeconds: 5
          periodSeconds: 5

