apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}
  labels:
    project: roboshop
    app: {{ .Values.appName }}
spec:
  replicas: 1
  selector:
    matchLabels:
      project: roboshop
      app: {{ .Values.appName }}
  template:
    metadata:
      labels:
        project: roboshop
        app: {{ .Values.appName }}
    spec:
      containers:
      - name: {{ .Values.appName }}
        image: public.ecr.aws/w8x4g9h7/roboshop-v3/{{ .Values.appName }}
        envFrom:
        - configMapRef:
            name: {{ .Values.appName }}
        readinessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5

