{{ if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: roboshop-{{ .Values.appName }}
spec:
  ingressClassName: nginx
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: roboshop-{{ .Values.appName }}
            port:
              number: {{ .Values.service.port }}
{{ end }}

