apiVersion: v1
kind: Service
  {{- template "app.metadata" . }}
spec:
  type: {{ .Values.service.type }}
  selector:
{{ include "app.labels" . | indent 4 }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}

